# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = mc.simpletrading
archives_name = simpletrading
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.8

# Mappings
parchment_mc_version = 1.21.8
parchment_version = 2025.07.20

# NeoForm (for common module - ModDevGradle)
neoform_version = 1.21.8-20250717.133445

# Dependencies
fabric_loader_version = 0.17.2
fabric_api_version = 0.133.4+1.21.8
neoforge_version = 21.8.33
mixin_extras = 0.4.1
