# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 2.0.1
maven_group = mc.simpletrading
archives_name = simpletrading
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.2

# NeoForm (for common module - ModDevGradle)
neoform_version = 26.2-2

# Dependencies
fabric_loader_version = 0.19.3
fabric_api_version = 0.157.0+26.2
neoforge_version = 26.2.0.59
mixin_extras = 0.5.4
