plugins {
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = rootProject.neoform_version

    parchment {
        minecraftVersion = rootProject.parchment_minecraft_version
        mappingsVersion = rootProject.parchment_mappings_version
    }
}

dependencies {
    compileOnly "org.spongepowered:mixin:0.8.7"
    compileOnly "io.github.llamalad7:mixinextras-common:$rootProject.mixin_extras"
    compileOnly "com.mojang:brigadier:1.0.500"
}
